from tkinter import *
from tkinter import ttk
import tkinter

# login=Tk()
# login.title('Đăng nhập')
# login.geometry('400x200+500+250')
# login.resizable(0,0)
# name_label=Label(login,text='Tên hiển thị:',font=('Times',15,'bold'))
# name_label.place(x=20,y=20)
# name_typing=Entry(login,font=('Times',15))
# name_typing.place(x=150,y=22)

# password_label=Label(login,text='Mật khẩu:',font=('Times',15,'bold'))
# password_label.place(x=20,y=60)
# password_typing=Entry(login,font=('Times',15))
# password_typing.place(x=150,y=62)


# save=IntVar()
# save_checked=Checkbutton(login,text='Nhớ mật khẩu',font=('Times',12),variable=save,onvalue=1,offvalue=0)
# save_checked.place(x=145,y=92)

# login_btn=Button(login,text='Đăng nhập',font=('Times',15,'bold'),padx=10,bd=5,relief=RIDGE,overrelief=RAISED)
# login_btn.place(x=150,y=130)


# mainloop()

def chu_thich():
    ct=Tk()
    ct.geometry('300x500')
    ct.title('Bảng chú thích')
    ct.resizable(0,0)
    def ct_kl():
        global lbl_kl,lbl_ct_1,lbl_ct_2,lbl_ct_3,lbl_ct_4,lbl_ct_5,lbl_ct_6,lbl_ct_7,lbl_ct_8,lbl_ct_9,lbl_ct_10,lbl_ct_11,lbl_ct_12,lbl_status,ct_colour
        ct_colour='#aae4e6'
        lbl_kl=Label(ct,text='* Khối lượng:',font=('Times',25,'bold','italic'),bg=ct_colour,fg='#ff4d00')
        lbl_kl.place(x=20,y=10)
        lbl_ct_1=Label(ct,text='+ Tấn:                 tấn theo hệ mét',font=('Times',15),bg=ct_colour)
        lbl_ct_1.place(x=20,y=60)
        lbl_ct_2=Label(ct,text='+ Tấn (UK):        tấn dài',font=('Times',15),bg=ct_colour)
        lbl_ct_2.place(x=20,y=90)
        lbl_ct_3=Label(ct,text='+ Tấn (US):        tấn ngắn',font=('Times',15),bg=ct_colour)
        lbl_ct_3.place(x=20,y=120)
        lbl_ct_4=Label(ct,text='+ Kg:                  kilogram',font=('Times',15),bg=ct_colour)
        lbl_ct_4.place(x=20,y=150)
        lbl_ct_5=Label(ct,text='+ g:                     gram',font=('Times',15),bg=ct_colour)
        lbl_ct_5.place(x=20,y=180)
        lbl_ct_6=Label(ct,text='+ mg:                  milligram',font=('Times',15),bg=ct_colour)
        lbl_ct_6.place(x=20,y=210)
        lbl_ct_7=Label(ct,text='+ lb:                   pound',font=('Times',15),bg=ct_colour)
        lbl_ct_7.place(x=20,y=240)
        lbl_ct_8=Label(ct,text='+ ct:                   carat',font=('Times',15),bg=ct_colour)
        lbl_ct_8.place(x=20,y=270)
        lbl_ct_9=Label(ct,text='+ oz:                  ounce',font=('Times',15),bg=ct_colour)
        lbl_ct_9.place(x=20,y=300)
        lbl_ct_10=Label(ct,text='+ gr:                  grain',font=('Times',15),bg=ct_colour)
        lbl_ct_10.place(x=20,y=330)
        lbl_ct_11=Label(ct,text='',font=('Times',15),bg=ct_colour)
        lbl_ct_11.place(x=20,y=360)
        lbl_ct_12=Label(ct,text='',font=('Times',15),bg=ct_colour)
        lbl_ct_12.place(x=20,y=390)
        pre_btn.configure(state=DISABLED)
        next_btn.configure(command=ct_nd)
        lbl_status=Label(ct,text='1/11',font=('Times',15,'bold'))
        lbl_status.place(x=130,y=450)
        
    def ct_nd():
        pre_btn.configure(state=NORMAL)
        pre_btn.configure(command=ct_kl)
        next_btn.configure(command=ct_đd)
        lbl_kl.configure(text='* Nhiệt độ:')
        lbl_ct_1.configure(text='+ °C:           độ Celsius')
        lbl_ct_2.configure(text='+ °F:           độ Fahrenheit')
        lbl_ct_3.configure(text='+ K:            độ Kelvin')
        lbl_ct_4.configure(text='+ °R:           độ Rankine')
        lbl_ct_5.configure(text='')
        lbl_ct_6.configure(text='')
        lbl_ct_7.configure(text='')
        lbl_ct_8.configure(text='')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_ct_11.configure(text='')
        lbl_ct_12.configure(text='')
        lbl_status.configure(text='2/11')
    def ct_đd ():
        pre_btn.configure(command=ct_nd)
        next_btn.configure(command=ct_dt)
        lbl_kl.configure(text='* Độ dài:       ')
        lbl_ct_1.configure(text='+ km:          kilometer       ')
        lbl_ct_2.configure(text='+ m:            meter              ')
        lbl_ct_3.configure(text='+ cm:          centimeter      ')
        lbl_ct_4.configure(text='+ mm:         millimeter       ')
        lbl_ct_5.configure(text='+ µm:          micrometer')
        lbl_ct_6.configure(text='+ nm:          nanometer')
        lbl_ct_7.configure(text='+ pm:          picometer')
        lbl_ct_8.configure(text='+ Å:            armstrong')
        lbl_ct_9.configure(text='+ inch:        inch')
        lbl_ct_10.configure(text='+ mi:           mile (dặm)')
        lbl_ct_11.configure(text='+ ft:             foot')
        lbl_ct_12.configure(text='+ yd:           yard')
        lbl_status.configure(text='3/11')
    def ct_dt ():
        pre_btn.configure(command=ct_đd)
        next_btn.configure(command=ct_tht)
        lbl_kl.configure(text='* Diện tích:    ')
        lbl_ct_1.configure(text='+ km2:           kilomet vuông  ')
        lbl_ct_2.configure(text='+ ha:              hectare              ')
        lbl_ct_3.configure(text='+ a:                are         ')
        lbl_ct_4.configure(text='+ m2:             met vuông     ')
        lbl_ct_5.configure(text='+ cm2:           centimet vuông ')
        lbl_ct_6.configure(text='+ ft2:             foot vuông   ')
        lbl_ct_7.configure(text='+ acre:           mẫu Anh       ')
        lbl_ct_8.configure(text='')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_ct_11.configure(text='')
        lbl_ct_12.configure(text='')
        lbl_status.configure(text='4/11')
    def ct_tht ():
        pre_btn.configure(command=ct_dt)
        next_btn.configure(command=ct_as)
        lbl_kl.configure(text='* Thể tích:                       ')
        lbl_ct_1.configure(text='+ m3:                      met khối         ')
        lbl_ct_2.configure(text='+ cm3:                    centimet khối     ')
        lbl_ct_3.configure(text='+ mm3:                   millimet khối      ')
        lbl_ct_4.configure(text='+ l:                         lít            ')
        lbl_ct_5.configure(text='+ ml:                      milli lít        ')
        lbl_ct_6.configure(text='+ bushel (US):       bushel hệ Mỹ           ')
        lbl_ct_7.configure(text='+ bushel (UK):      bushel hệ Anh           ')
        lbl_ct_8.configure(text='+ gal (US):            gallon hệ Mỹ         ')
        lbl_ct_9.configure(text='+ gal (UK):           gallon hệ Anh         ')
        lbl_ct_10.configure(text='+ ft3:                     foot khối       ')
        lbl_status.configure(text='5/11')
    def ct_as ():
        pre_btn.configure(command=ct_tht)
        next_btn.configure(command=ct_vt)
        lbl_kl.configure(text='* Áp suất:                 ')
        lbl_ct_1.configure(text='+ Pa:           pascal        ')
        lbl_ct_2.configure(text='+ bar:          bar                ')
        lbl_ct_3.configure(text='+ at:            atmosphere kỹ thuật        ')
        lbl_ct_4.configure(text='+ atm:         atmosphere tiêu chuẩn        ')
        lbl_ct_5.configure(text='+ Torr:        torr')
        lbl_ct_6.configure(text='+ lbf/in2:    pound trên inch vuông')
        lbl_ct_7.configure(text='+ mmHg:    millimet thủy ngân')
        lbl_ct_8.configure(text='')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_status.configure(text='6/11')
    def ct_vt ():
        pre_btn.configure(command=ct_as)
        next_btn.configure(command=ct_nl)
        lbl_kl.configure(text='* Vận tốc:                 ')
        lbl_ct_1.configure(text='+ km/h:           kilomet trên giờ                 ')
        lbl_ct_2.configure(text='+ m/s:             met trên giây                 ')
        lbl_ct_3.configure(text='+ mph:           dặm trên giờ                 ')
        lbl_ct_4.configure(text='+ ft/s:             foot trên giây                 ')
        lbl_ct_5.configure(text='+ kn (kt):        hải lý trên giờ')
        lbl_ct_6.configure(text='+ M:              tốc độ âm thanh ')
        lbl_ct_7.configure(text='')
        lbl_ct_8.configure(text='')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_status.configure(text='7/11')
    def ct_nl ():
        pre_btn.configure(command=ct_vt)
        next_btn.configure(command=ct_cs)
        lbl_kl.configure(text='* Năng lượng:                      ')
        lbl_ct_1.configure(text='+ J:               jun                      ')
        lbl_ct_2.configure(text='+ kJ:             kilo jun                      ')
        lbl_ct_3.configure(text='+ cal:            calo                      ')
        lbl_ct_4.configure(text='+ kcal:          kilo calo                      ')
        lbl_ct_5.configure(text='+ Btu:          đơn vị nhiệt Anh')
        lbl_ct_6.configure(text='+ kWh:         kilowatt trên giờ')
        lbl_ct_7.configure(text='+ eV:           electron volt')
        lbl_ct_8.configure(text='+ MeV:        mega electron volt')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_status.configure(text='8/11')
    def ct_cs ():
        pre_btn.configure(command=ct_nl)
        next_btn.configure(command=ct_g)
        lbl_kl.configure(text='* Công suất:                        ')
        lbl_ct_1.configure(text='+ W:           watt                        ')
        lbl_ct_2.configure(text='+ kW:          kilowatt                        ')
        lbl_ct_3.configure(text='+ MW:        megawatt                        ')
        lbl_ct_4.configure(text='+ hp:           mã lực                        ')
        lbl_ct_5.configure(text='+ Btu/s: đơn vị nhiệt Anh trên giây')
        lbl_ct_6.configure(text='+ dBm:       decibel-milliwatt')
        lbl_ct_7.configure(text='+ cal/h:       calo trên giờ')
        lbl_ct_8.configure(text='')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_status.configure(text='9/11')
    def ct_g ():
        pre_btn.configure(command=ct_cs)
        next_btn.configure(command=ct_dl)
        next_btn.configure(state=NORMAL)    
        lbl_kl.configure(text='* Góc:                  ')
        lbl_ct_1.configure(text='+ °:              độ                  ')
        lbl_ct_2.configure(text="+ ':              phút                  ")
        lbl_ct_3.configure(text='+ ":              giây                  ')
        lbl_ct_4.configure(text='+ rad:          radian                  ')
        lbl_ct_5.configure(text='+ ^g:           gradian')
        lbl_ct_6.configure(text='')
        lbl_ct_7.configure(text='')
        lbl_ct_8.configure(text='')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_status.configure(text='10/11')
    def ct_dl ():
        next_btn.configure(state=DISABLED)
        pre_btn.configure(command=ct_g)
        lbl_kl.configure(text='* Dữ liệu:               ')
        lbl_ct_1.configure(text='+ b:                 bit                ')
        lbl_ct_2.configure(text='+ B:                byte                 ')
        lbl_ct_3.configure(text='+ kB:              kilobyte')
        lbl_ct_4.configure(text='+ MB:            megabyte')
        lbl_ct_5.configure(text='+ GB:            gigabyte')
        lbl_ct_6.configure(text='+ TB:             tetrabyte ')
        lbl_ct_7.configure(text='+ PB:             petabyte')
        lbl_ct_8.configure(text='')
        lbl_ct_9.configure(text='')
        lbl_ct_10.configure(text='')
        lbl_status.configure(text='11/11')


    next_btn=Button(ct,text='>>>',width=5,bd=5,relief=RIDGE,overrelief=RAISED)
    next_btn.place(x=200,y=450)
    pre_btn=Button(ct,text='<<<',width=5,bd=5,relief=RIDGE,overrelief=RAISED,state=DISABLED)
    pre_btn.place(x=50,y=450)
    ct_kl()
    ct['background']=ct_colour
    ct.mainloop()
chu_thich()